#!/bin/bash

# ==== Aliases ====

alias ls="ls -G -1"
alias timestamp='date "+%Y.%m.%d.%H.%M"'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
alias lsip='curl -s http://checkip.dyndns.org | sed "s/[a-zA-Z/<> :]//g"'
alias servedir='python -m SimpleHTTPServer'
