#!/bin/bash

# ==== Path Lookups ====

export PATH=.:~/Dropbox/bin:/usr/local/bin:/usr/local/mysql/bin:/opt/local/bin:/opt/local/sbin:~/bin:$PATH;

export NODE_PATH=/usr/local/lib/node_modules:$NODE_PATH;
