#!/bin/bash

# ==== Shell Prompt ==== 

# colors
BOLD="\[$(tput bold)\]"
RED="\[$(tput setaf 1)\]"
WHITE="\[$(tput setaf 7)\]"
LBLUE="\[$(tput setaf 6)\]"
BLUE="\[$(tput setaf 4)\]"
RESET="\[$(tput sgr0)\]"

export PS1="\n$BOLD$RED\u$WHITE on$LBLUE \h$WHITE in$BLUE \w$WHITE $BLUE\n➤ $RESET"
